### ISSUE TITLE
Middleware/Federation: SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by rajansandeep** [coredns/coredns#1030]
When I try to start up using Federation after #1027 , I see the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14fb560]

goroutine 1 [running]:
github.com/coredns/coredns/core/dnsserver.(*Config).registerHandler(0xc42015c120, 0x0, 0x0)
	/Users/srajan/go/src/github.com/coredns/coredns/core/dnsserver/register.go:135 +0x40
github.com/coredns/coredns/core/dnsserver.NewServer(0xc42034ffe5, 0xb, 0xc42000e0c0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/srajan/go/src/github.com/coredns/coredns/core/dnsserver/server.go:73 +0x32f
github.com/coredns/coredns/core/dnsserver.(*dnsContext).MakeServers(0xc420366580, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/srajan/go/src/github.com/coredns/coredns/core/dnsserver/register.go:95 +0x302
github.com/mholt/caddy.startWithListenerFds(0x2d20380, 0xc42030d680, 0xc4201669c0, 0x0, 0x0, 0x0)
	/Users/srajan/go/src/github.com/mholt/caddy/caddy.go:442 +0x98
github.com/mholt/caddy.Start(0x2d20380, 0xc42030d680, 0x2d20380, 0xc42030d680, 0x0)
	/Users/srajan/go/src/github.com/mholt/caddy/caddy.go:429 +0xe0
github.com/coredns/coredns/coremain.Run()
	/Users/srajan/go/src/github.com/coredns/coredns/coremain/run.go:94 +0x5c2
main.main()
	/Users/srajan/go/src/github.com/coredns/coredns/coredns.go:8 +0x20

Process finished with exit code 2
```

The config I've used is as follows:

```
.:53 {
      health
      errors
      log
      kubernetes cluster.local {
        endpoint http://localhost:8080
        pods verified
      }
      federation cluster.local {
        prod prod.feddomain.com
      }
    }
```

**Comment by chrisohaver** [comment]
This was fixed by #1029
