### ISSUE TITLE
TestNewServer hangs

### ISSUE THREAD

**Issue by rdrozhdzh** [coredns/coredns#1785]
```
=== RUN   TestNewServer
SIGQUIT: quit
PC=0x45b643 m=0 sigcode=0
goroutine 4 [syscall]:
runtime.notetsleepg(0x846700, 0x773556ee, 0x16)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/lock_futex.go:227 +0x42 fp=0xc420043760 sp=0xc420043730 pc=0x410322
runtime.timerproc(0x8466e0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/time.go:261 +0x2e7 fp=0xc4200437d8 sp=0xc420043760 pc=0x449b07
runtime.goexit()
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200437e0 sp=0xc4200437d8 pc=0x45a0a1
created by runtime.(*timersBucket).addtimerLocked
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/time.go:160 +0x107
goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200ee5a0, 0x6da588, 0xd, 0x6e72d8, 0x475601)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc4200ee000)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc4200ee000, 0xc420065d90)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:777 +0xd0
testing.runTests(0xc4200a6260, 0x83e940, 0x6, 0x6, 0x411059)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc4200ec000, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:978 +0x171
main.main()
	_testmain.go:102 +0x208
goroutine 24 [chan receive]:
github.com/coredns/coredns/plugin/pkg/dnstest.NewServer(0x6e72d0, 0x81fca7)
	/home/travis/gopath/src/github.com/coredns/coredns/plugin/pkg/dnstest/server.go:37 +0x2fd
github.com/coredns/coredns/plugin/pkg/dnstest.TestNewServer(0xc4200ee5a0)
	/home/travis/gopath/src/github.com/coredns/coredns/plugin/pkg/dnstest/server_test.go:10 +0x42
testing.tRunner(0xc4200ee5a0, 0x6e72d8)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:824 +0x2e0
goroutine 25 [IO wait]:
internal/poll.runtime_pollWait(0x2b3e2b76df00, 0x72, 0xc420128a00)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200ec098, 0x72, 0xc420019f00, 0x28, 0x0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4200ec098, 0xc420128a00, 0x200, 0x200)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).ReadMsg(0xc4200ec080, 0xc420128a00, 0x200, 0x200, 0xc420019f50, 0x28, 0x28, 0x0, 0x0, 0x0, ...)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/internal/poll/fd_unix.go:231 +0x1f1
net.(*netFD).readMsg(0xc4200ec080, 0xc420128a00, 0x200, 0x200, 0xc420019f50, 0x28, 0x28, 0x456300, 0xc420001380, 0x0, ...)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/net/fd_unix.go:214 +0x90
net.(*UDPConn).readMsg(0xc42009e030, 0xc420128a00, 0x200, 0x200, 0xc420019f50, 0x28, 0x28, 0x2b3e2b719000, 0x0, 0xc420051cc0, ...)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/net/udpsock_posix.go:59 +0x91
net.(*UDPConn).ReadMsgUDP(0xc42009e030, 0xc420128a00, 0x200, 0x200, 0xc420019f50, 0x28, 0x28, 0x72, 0x2b3e2b719000, 0x0, ...)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/net/udpsock.go:139 +0xaa
github.com/miekg/dns.ReadFromSessionUDP(0xc42009e030, 0xc420128a00, 0x200, 0x200, 0x200, 0x200, 0x842fe0, 0xc420051e20)
	/home/travis/gopath/src/github.com/miekg/dns/udp.go:26 +0xb4
github.com/miekg/dns.(*Server).readUDP(0xc4200de0c0, 0xc42009e030, 0x77359400, 0x85fce0, 0x707101, 0x85fce0, 0x2b3e2b7a9030, 0x85fce0, 0x2b3e2b7a9001)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:637 +0xbc
github.com/miekg/dns.(*defaultReader).ReadUDP(0xc42009e048, 0xc42009e030, 0x77359400, 0x2b3e2b7a9000, 0xc42011ceb0, 0x1, 0x0, 0x707200, 0xc42011ceb0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:254 +0x46
github.com/miekg/dns.(*Server).serveUDP(0xc4200de0c0, 0xc42009e030, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:507 +0x13c
github.com/miekg/dns.(*Server).ActivateAndServe(0xc4200de0c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/miekg/dns/server.go:397 +0x22e
created by github.com/coredns/coredns/plugin/pkg/dnstest.NewServer
	/home/travis/gopath/src/github.com/coredns/coredns/plugin/pkg/dnstest/server.go:33 +0x2aa
rax    0xfffffffffffffffc
rbx    0x3b9a8cee
rcx    0x45b643
rdx    0x0
rdi    0x846700
rsi    0x0
rbp    0xc4200436e8
rsp    0xc4200436a0
r8     0x0
r9     0x0
r10    0xc4200436d8
r11    0x206
r12    0x2b3e2b76df00
r13    0xa8
r14    0xa7
r15    0xaa
rip    0x45b643
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/coredns/coredns/plugin/pkg/dnstest	600.004s
make: *** [travis] Error 1
```

**Comment by rdrozhdzh** [comment]
Seems the cause is in incorrect `NewServer()` function

```
func NewServer(f dns.HandlerFunc) *Server {
	dns.HandleFunc(".", f)

	ch1 := make(chan bool)
	ch2 := make(chan bool)

	p, _ := net.ListenPacket("udp", ":0")
	l, _ := net.Listen("tcp", p.LocalAddr().String())

	s1 := &dns.Server{PacketConn: p}
	s2 := &dns.Server{Listener: l}
	s1.NotifyStartedFunc = func() { close(ch1) }
	s2.NotifyStartedFunc = func() { close(ch2) }
	go s1.ActivateAndServe()
	go s2.ActivateAndServe()

	<-ch1
	<-ch2

	return &Server{s1: s1, s2: s2, Addr: p.LocalAddr().String()}
}
```

Here we create UDP listener on arbitrary port, and then use the same port to create TCP listener. However, the TCP port may be in use, and we'll get nil and error. Since we don't check errors, we hang later at line
```
<-ch2
```

**Comment by miekg** [comment]
Ah nice. Just switch the lines and get the tcp one first. Less chance that
UDP is taken.

**Comment by rdrozhdzh** [comment]
Makes sense.
I also thought of retrying several times in loop, but I'm not sure if it will give us different port on next attempt (assuming that we close previous listener)

**Comment by rdrozhdzh** [comment]
I just faced another intermittently failing test - proxy.TestStop()
It complained about "Test 0, Expected healthchecks to hit test server, got none"
I restarted the job and it passed successfully

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] TestNewServer..." ]
>I just faced another intermittently failing test - proxy.TestStop()
>It complained about "Test 0, Expected healthchecks to hit test server, got none"
>I restarted the job and it passed successfully

yeah, racy because of sleeps/timing being used.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
Fixed via #1786

**Comment by rdrozhdzh** [comment]
With #1786 I've got the panic 
```
--- FAIL: TestForwardTruncated (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xbf7162]
goroutine 705 [running]:
testing.tRunner.func1(0xc42021d3b0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:742 +0x567
panic(0xcbf140, 0x11826f0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502 +0x24a
github.com/coredns/coredns/plugin/pkg/dnstest.(*Server).Close(0x0)
	/home/travis/gopath/src/github.com/coredns/coredns/plugin/pkg/dnstest/server.go:51 +0x42
panic(0xcbf140, 0x11826f0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502 +0x24a
github.com/coredns/coredns/plugin/forward.TestForwardTruncated(0xc42021d3b0)
	/home/travis/gopath/src/github.com/coredns/coredns/plugin/forward/truncated_test.go:91 +0x2c3
testing.tRunner(0xc42021d3b0, 0xda6890)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:824 +0x565
FAIL	github.com/coredns/coredns/plugin/forward	29.221s

```
So, the probability of UPD & TCP port conflicts is still quite high. We need to come up with a better solution.

**Comment by miekg** [comment]
I remain unconvinced we should do #1799, until it becomes too problematic to even run tests.

**Comment by miekg** [comment]
hmmm
~~~
--- FAIL: TestForwardTruncated (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x927c42]
goroutine 640 [running]:
testing.tRunner.func1(0xc42055a0f0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:742 +0x29d
panic(0x9db960, 0xe146b0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502 +0x229
github.com/coredns/coredns/plugin/pkg/dnstest.(*Server).Close(0x0)
	/home/travis/gopath/src/github.com/coredns/coredns/plugin/pkg/dnstest/server.go:51 +0x22
panic(0x9db960, 0xe146b0)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:502 +0x229
github.com/coredns/coredns/plugin/forward.TestForwardTruncated(0xc42055a0f0)
	/home/travis/gopath/src/github.com/coredns/coredns/plugin/forward/truncated_test.go:91 +0x1a4
testing.tRunner(0xc42055a0f0, 0xac2d70)
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.10.1.linux.amd64/src/testing/testing.go:824 +0x2e0
FAIL	github.com/coredns/coredns/plugin/forward	29.026s
make: *** [travis] Error 1
~~~

**Comment by miekg** [comment]
Getting more annoyed by this one. Travis seems particularly bad in having a port open for tcp and then not for udp

**Comment by rdrozhdzh** [comment]
so, would you like the solution like #1799 to be implemented?
Or we can just panic in `NewServer()` - at least it would be easier to understand why test failed

**Comment by miekg** [comment]
your retry is probably the best way forward

**Comment by rdrozhdzh** [comment]
let's try it, anyway this change will only affect the test code, not coredns itself

**Comment by rdrozhdzh** [comment]
reopened #1799
