### ISSUE TITLE
My coredns crashed.

### ISSUE THREAD

**Issue by dingcj** [coredns/coredns#2336]
Hi, 
My coredns crashed and My coredns crashed and details are as follows. 
*  version
````
CoreDNS-1.2.6
linux/amd64, go1.11.2, 756749c
````
* Corefile
````
.:1053 {
        cache
        log
        prometheus :8089
        forward . 119.29.29.29 182.254.116.116 114.114.114.114 114.114.115.115 223.5.5.5 223.6.6.6 123.125.81.6 140.207.198.6 180.76.76.76 {

        }
}
`````
* logs:
````
panic: too many concurrent operations on a single file or socket (max 1048575) [recovered]
        panic: too many concurrent operations on a single file or socket (max 1048575)

goroutine 4498975 [running]:
internal/poll.(*fdMutex).rwlock(0xc000522780, 0x0, 0xc2c7115900)
        /tmp/tmp.ojxohJ1Ye7/go/src/internal/poll/fd_mutex.go:147 +0x13f
internal/poll.(*FD).writeLock(0xc000522780, 0xc2c74107cc, 0x10)
        /tmp/tmp.ojxohJ1Ye7/go/src/internal/poll/fd_mutex.go:239 +0x32
internal/poll.(*FD).WriteMsg(0xc000522780, 0xc27ba06a20, 0x25, 0x26, 0xc273edcaa0, 0x20, 0x20, 0x1b54fc0, 0xc2c7115900, 0x0, ...)
        /tmp/tmp.ojxohJ1Ye7/go/src/internal/poll/fd_unix.go:345 +0x58
net.(*netFD).writeMsg(0xc000522780, 0xc27ba06a20, 0x25, 0x26, 0xc273edcaa0, 0x20, 0x20, 0x1b54fc0, 0xc2c7115900, 0xc2c7594e30, ...)
        /tmp/tmp.ojxohJ1Ye7/go/src/net/fd_unix.go:232 +0xaa
net.(*UDPConn).writeMsg(0xc00000c5b0, 0xc27ba06a20, 0x25, 0x26, 0xc273edcaa0, 0x20, 0x20, 0xc2c73d9a10, 0x69b53b, 0xc2799acb80, ...)
        /tmp/tmp.ojxohJ1Ye7/go/src/net/udpsock_posix.go:94 +0x114
net.(*UDPConn).WriteMsgUDP(0xc00000c5b0, 0xc27ba06a20, 0x25, 0x26, 0xc273edcaa0, 0x20, 0x20, 0xc2c73d9a10, 0x0, 0x0, ...)
        /tmp/tmp.ojxohJ1Ye7/go/src/net/udpsock.go:189 +0xb5
github.com/miekg/dns.WriteToSessionUDP(0xc00000c5b0, 0xc27ba06a20, 0x25, 0x26, 0xc2786bb8a0, 0x0, 0x0, 0x0)
        /tmp/tmp.ojxohJ1Ye7/g/src/github.com/miekg/dns/udp.go:52 +0xa8
github.com/miekg/dns.(*response).Write(0xc2c75b2200, 0xc27ba06a20, 0x25, 0x26, 0x0, 0x0, 0x8)
        /tmp/tmp.ojxohJ1Ye7/g/src/github.com/miekg/dns/server.go:763 +0x300
github.com/miekg/dns.(*response).WriteMsg(0xc2c75b2200, 0xc2c74e4900, 0xc2c74e4900, 0x3)
        /tmp/tmp.ojxohJ1Ye7/g/src/github.com/miekg/dns/server.go:751 +0x8d
github.com/coredns/coredns/request.(*ScrubWriter).WriteMsg(0xc278661780, 0xc2c74e4900, 0xc2c74e47e0, 0x1b81940)
        /tmp/tmp.ojxohJ1Ye7/g/src/github.com/coredns/coredns/request/writer.go:19 +0xae
github.com/coredns/coredns/core/dnsserver.DefaultErrorFunc(0x1b73940, 0xc2c739f770, 0x1b81940, 0xc278661780, 0xc2c74e47e0, 0x2)
        /tmp/tmp.ojxohJ1Ye7/g/src/github.com/coredns/coredns/core/dnsserver/server.go:351 +0x227
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS.func1(0xc2c7595d28, 0xc2c7595d38, 0xc2c74e47e0)
        /tmp/tmp.ojxohJ1Ye7/g/src/github.com/coredns/coredns/core/dnsserver/server.go:213 +0x9c
````

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/coredns] My coredns crashe..." ]
>Hi,
>My coredns crashed and My coredns crashed and details are as follows.

You have a resolving loop. Load the *loop* plugin to have it crash (again), but 
with a nicer message.
