### ISSUE TITLE
metrics reload is flacky

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#2410]
~~~
=== RUN   TestReloadMetricsHealth
panic: sync: negative WaitGroup counter
goroutine 1675 [running]:
sync.(*WaitGroup).Add(0xc000653230, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/sync/waitgroup.go:74 +0x137
sync.(*WaitGroup).Done(0xc000653230)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/sync/waitgroup.go:99 +0x34
github.com/coredns/coredns/core/dnsserver.(*Server).Stop.func1(0xc000653200, 0xc0009fa480)
	/home/travis/gopath/src/github.com/coredns/coredns/core/dnsserver/server.go:167 +0x36
created by github.com/coredns/coredns/core/dnsserver.(*Server).Stop
	/home/travis/gopath/src/github.com/coredns/coredns/core/dnsserver/server.go:166 +0x7c
FAIL	github.com/coredns/coredns/test	40.699s
make: *** [travis] Error 1
The command "make TEST_TYPE=$TEST_TYPE travis" exited with 2.
~~~

**Comment by daniel-garcia** [comment]
I'll pick this up.

**Comment by fturib** [comment]
NOTE: @daniel-garcia will not be able to work on it before mid-feb .. so if someone is willing, please add to this comment and go over. Thanks!

**Comment by miekg** [comment]
is anything happening here? Otherwise I'll close it

**Comment by miekg** [comment]
This seems to happen again:
~~~
--- PASS: TestAutoAXFR (1.10s)
--- PASS: TestAuto (2.60s)
PASS
panic: sync: negative WaitGroup counter
goroutine 2013 [running]:
sync.(*WaitGroup).Add(0xc0002e0930, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/sync/waitgroup.go:74 +0x20c
sync.(*WaitGroup).Done(...)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/sync/waitgroup.go:99
github.com/coredns/coredns/core/dnsserver.(*Server).Stop.func1(0xc0002e0900, 0xc00079cc00)
	/home/travis/gopath/src/github.com/coredns/coredns/core/dnsserver/server.go:172 +0x4e
created by github.com/coredns/coredns/core/dnsserver.(*Server).Stop
	/home/travis/gopath/src/github.com/coredns/coredns/core/dnsserver/server.go:171 +0x8d
FAIL	github.com/coredns/coredns/test	21.280s
make: *** [travis] Error 1
The command "make TEST_TYPE=$TEST_TYPE travis" exited with 2.
~~~

**Comment by miekg** [comment]
prolly downing the server to quickly or someting

**Comment by miekg** [comment]
@daniel-garcia are you working on this?

**Comment by miekg** [comment]
this seems fixed in later versions.
