### ISSUE TITLE
plugin/file query deadlock

### ISSUE THREAD

**Issue by C0reFast** [coredns/coredns#2975]
When we running coredns using file plugin for a while, the coredns did'nt reponse any query served by file plugin,meanwhile, the k8s plugin still working. here are some infomation, I killed the coredns process with ABRT signal and find lots of goroutine stuck at `plugin/file/lookup.go:36`, is `z.reloadMu.RLock()`.

the coredns version we use: 
```
# /usr/bin/coredns -version
CoreDNS-1.5.2
linux/amd64, go1.12.6, d933f63
``` 
the corefile:
```
nvsdbl.example.com. {
    kubernetes {
        endpoint https://nvsdbl.k8.example.com:6443
        tls /etc/coredns/k8s-client.cert /etc/coredns/k8s-client.key /etc/coredns/k8s-ca.cert
        ttl 30
    }
    log
    prometheus 0.0.0.0:9153
}

example.com {
    file /etc/coredns/example.com.signed {
        reload 5s
    }
    log
    prometheus 0.0.0.0:9153
}

```

when we use `queryperf` to benchmark coredns, about 5 or 10 seconds the coredns will get stuck. the command and ouput is:
```
# ./queryperf -q 100 -d x.t -s 10.13.2.35 -l 1000                                                                                                                             

DNS Query Performance Testing Tool
Version: $Id: queryperf.c,v 1.12 2007/09/05 07:36:04 marka Exp $
[Status] Processing input data
[Status] Sending queries (beginning with 10.13.2.35)
[Timeout] Query timed out: msg id 47458
[Timeout] Query timed out: msg id 47550
[Timeout] Query timed out: msg id 47557
[Timeout] Query timed out: msg id 47564
[Timeout] Query timed out: msg id 47625
[Timeout] Query timed out: msg id 47640
[Timeout] Query timed out: msg id 47650
[Timeout] Query timed out: msg id 47651
[Timeout] Query timed out: msg id 47656
[Timeout] Query timed out: msg id 47657
[Timeout] Query timed out: msg id 47706
[Timeout] Query timed out: msg id 47707
[Timeout] Query timed out: msg id 47719
[Timeout] Query timed out: msg id 47723
[Timeout] Query timed out: msg id 47732
[Timeout] Query timed out: msg id 47735
[Timeout] Query timed out: msg id 47739
[Timeout] Query timed out: msg id 47740
```

and the shorten dumped stack info:
```
coredns[23120]: goroutine 175906 [semacquire, 1 minutes]:
coredns[23120]: sync.runtime_SemacquireMutex(0xc00063838c, 0x4bdf00)
coredns[23120]: /tmp/tmp.nhEpihdcHr/go/src/runtime/sema.go:71 +0x3d
coredns[23120]: sync.(*RWMutex).RLock(...)
coredns[23120]: /tmp/tmp.nhEpihdcHr/go/src/sync/rwmutex.go:50
coredns[23120]: github.com/coredns/coredns/plugin/file.(*Zone).Lookup(0xc000638280, 0x1cfd680, 0xc001cd8a50, 0xc002274a20, 0x1d1ce80, 0xc0011b1100, 0x0, 0x0, 0x0, 0xc001ae60dc, ...)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/src/github.com/coredns/coredns/plugin/file/lookup.go:36 +0x3202
coredns[23120]: github.com/coredns/coredns/plugin/file.File.ServeDNS(0x0, 0x0, 0xc000696720, 0xc00035b0f0, 0x1, 0x1, 0x1cfd680, 0xc001cd8a50, 0x1d1ce80, 0xc0011b1100, ...)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/src/github.com/coredns/coredns/plugin/file/file.go:82 +0x29e
coredns[23120]: github.com/coredns/coredns/plugin.NextOrFailure(0x19c5c23, 0x3, 0x1cd9c40, 0xc000426f60, 0x1cfd680, 0xc001cd8a50, 0x1d1ce80, 0xc0011b1100, 0xc002274a20, 0x0, ...)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/src/github.com/coredns/coredns/plugin/plugin.go:80 +0xe3
coredns[23120]: github.com/coredns/coredns/plugin/log.Logger.ServeDNS(0x1cd9c40, 0xc000426f60, 0xc00016e900, 0x1, 0x1, 0x1a76680, 0x2b9c3e0, 0x10, 0x10, 0x1cfd680, ...)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/src/github.com/coredns/coredns/plugin/log/log.go:35 +0x384
coredns[23120]: github.com/coredns/coredns/plugin.NextOrFailure(0x19ce11b, 0xa, 0x1cd9d00, 0xc000102ff0, 0x1cfd680, 0xc001cd8a50, 0x1d1ce80, 0xc0011b10c0, 0xc002274a20, 0x0, ...)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/src/github.com/coredns/coredns/plugin/plugin.go:80 +0xe3
coredns[23120]: github.com/coredns/coredns/plugin/metrics.(*Metrics).ServeDNS(0xc000480120, 0x1cfd680, 0xc001cd8a50, 0x1d1cfa0, 0xc001d60a80, 0xc002274a20, 0x40c368, 0x30, 0x18d2200)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/src/github.com/coredns/coredns/plugin/metrics/handler.go:27 +0x273
coredns[23120]: github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS(0xc0005da8a0, 0x1cfd680, 0xc001cd8a50, 0x1d1cfa0, 0xc001d60a80, 0xc002274a20)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/src/github.com/coredns/coredns/core/dnsserver/server.go:242 +0x6d4
coredns[23120]: github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1(0x1d1ed40, 0xc000c54cc0, 0xc002274a20)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/src/github.com/coredns/coredns/core/dnsserver/server.go:115 +0xb0
coredns[23120]: github.com/miekg/dns.HandlerFunc.ServeDNS(0xc00095e220, 0x1d1ed40, 0xc000c54cc0, 0xc002274a20)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/pkg/mod/github.com/miekg/dns@v1.1.14/server.go:37 +0x44
coredns[23120]: github.com/miekg/dns.(*Server).serveDNS(0xc000a4ad00, 0xc0010a5000, 0x27, 0x200, 0xc000c54cc0)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/pkg/mod/github.com/miekg/dns@v1.1.14/server.go:603 +0x2bc
coredns[23120]: github.com/miekg/dns.(*Server).serveUDPPacket(0xc000a4ad00, 0xc000b623d0, 0xc0010a5000, 0x27, 0x200, 0xc000bea100, 0xc0009c18e0)
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/pkg/mod/github.com/miekg/dns@v1.1.14/server.go:549 +0xb2
coredns[23120]: created by github.com/miekg/dns.(*Server).serveUDP
coredns[23120]: /tmp/tmp.nhEpihdcHr/g/pkg/mod/github.com/miekg/dns@v1.1.14/server.go:479 +0x27a

```
the completed dumped file can see the attachment:
[dump-34.txt](https://github.com/coredns/coredns/files/3358210/dump-34.txt)

**Comment by miekg** [comment]
probably can simplify the locking considerably here. Esp no apexMu was added, which is protects the *Tree and apex records. 

Still pondering if a pointer update is safe according to the Go memory model; than we don't need locking at all

**Comment by miekg** [comment]
Was this only with 1.5.2. or earlier versions as well?

**Comment by C0reFast** [comment]
> Was this only with 1.5.2. or earlier versions as well?
> […](#)
> On Thu, 4 Jul 2019, 10:10 Miek Gieben, ***@***.***> wrote: /plugin: file /label: bug /label: kubernetes

we test verison 1.5.0 and 1.5.2, all have the same issue, and we also test version 1.2.2, seems ok, but 1.2.2 used more memory, during the querperf test, the process memory grows from 20MB to 3.7GB.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/file q..." ]
>> Was this only with 1.5.2. or earlier versions as well?
>> […](#)
>> On Thu, 4 Jul 2019, 10:10 Miek Gieben, ***@***.***> wrote: /plugin: file /label: bug /label: kubernetes
>
>we test verison 1.5.0 and 1.5.2, all have the same issue, and we also test version 1.2.2, seems ok, 

ah ok. good.


> but 1.2.2 used more memory, during the querperf test, the process memory grows from 20MB to 3.7GB.

that probably down to the Go version used to compile it .

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
can you try  #3024 ? It's a bigger PR than I would have liked, but it simplifies the whole locking dance (have only one). This can still dead lock obvs.

**Comment by C0reFast** [comment]
> can you try #3024 ? It's a bigger PR than I would have liked, but it simplifies the whole locking dance (have only one). This can still dead lock obvs.

the code seems works fine, I benchmarked about 10 minutes and no dead lock occurred, i will grey upgrade more hosts to see there will be any problems in the production env.

**Comment by miekg** [comment]
thank you!
