### ISSUE TITLE
plugin/hosts crashing on function "LookupStaticHostV4" when debug enabled 

### ISSUE THREAD

**Issue by dirk-w85** [coredns/coredns#3074]
CoreDNS Version:  CoreDNS-1.6.0
linux/amd64, go1.12.7, 0a218d3

CoreFile:
```
(LabDefaults) {
    prometheus :9253
    log
    errors
}
example.com:53 {
    debug
    log
    root /etc/coredns/
    hosts example.hosts
}
```

example.hosts file:
```
192.168.1.10    example.com            example
fdfc:a744:27b5:3b0e::1  example.com example
```

Log:
```
Jul 31 17:35:53 infra-02 coredns: panic: runtime error: invalid memory address or nil pointer dereference
Jul 31 17:35:53 infra-02 coredns: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x142e9ce]
Jul 31 17:35:53 infra-02 coredns: goroutine 69 [running]:
Jul 31 17:35:53 infra-02 coredns: github.com/coredns/coredns/plugin/hosts.(*Hostsfile).LookupStaticHostV4(0xc000269680, 0xc0001bfca0, 0x1b, 0xc0001bfca0, 0x1b, 0xc0001bf3e0)
Jul 31 17:35:53 infra-02 coredns: /tmp/tmp.SQtMN80KzX/g/src/github.com/coredns/coredns/plugin/hosts/hostsfile.go:222 +0xae
Jul 31 17:35:53 infra-02 coredns: github.com/coredns/coredns/plugin/hosts.Hosts.ServeDNS(0x0, 0x0, 0xc000269680, 0xc0000feaf0, 0x1, 0x1, 0x1d370e0, 0xc0003ac330, 0x1d56ae0, 0xc0003a05c0, ...)
Jul 31 17:35:53 infra-02 coredns: /tmp/tmp.SQtMN80KzX/g/src/github.com/coredns/coredns/plugin/hosts/hosts.go:48 +0x695
Jul 31 17:35:53 infra-02 coredns: github.com/coredns/coredns/plugin.NextOrFailure(0x19f068f, 0x3, 0x1d133a0, 0xc000352210, 0x1d370e0, 0xc0003ac330, 0x1d56ae0, 0xc0003a05c0, 0xc0003b4090, 0x0, ...)
Jul 31 17:35:53 infra-02 coredns: /tmp/tmp.SQtMN80KzX/g/src/github.com/coredns/coredns/plugin/plugin.go:80 +0xe3
Jul 31 17:35:53 infra-02 coredns: github.com/coredns/coredns/plugin/log.Logger.ServeDNS(0x1d133a0, 0xc000352210, 0xc00032df20, 0x1, 0x1, 0x0, 0x1d370e0, 0xc0003ac330, 0x1d56c00, 0xc0003a2500, ...)
Jul 31 17:35:53 infra-02 coredns: /tmp/tmp.SQtMN80KzX/g/src/github.com/coredns/coredns/plugin/log/log.go:36 +0x38c
Jul 31 17:35:53 infra-02 coredns: github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS(0xc0003446c0, 0x1d370e0, 0xc0003ac330, 0x1d56c00, 0xc0003a2500, 0xc0003b4090)
Jul 31 17:35:53 infra-02 coredns: /tmp/tmp.SQtMN80KzX/g/src/github.com/coredns/coredns/core/dnsserver/server.go:242 +0x6d4
Jul 31 17:35:53 infra-02 coredns: github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1(0x1d589a0, 0xc0003a8480, 0xc0003b4090)
Jul 31 17:35:53 infra-02 coredns: /tmp/tmp.SQtMN80KzX/g/src/github.com/coredns/coredns/core/dnsserver/server.go:115 +0xb0
Jul 31 17:35:53 infra-02 coredns: github.com/miekg/dns.HandlerFunc.ServeDNS(0xc0002a1900, 0x1d589a0, 0xc0003a8480, 0xc0003b4090)
Jul 31 17:35:53 infra-02 coredns: /tmp/tmp.SQtMN80KzX/g/pkg/mod/github.com/miekg/dns@v1.1.15/server.go:37 +0x44
Jul 31 17:35:53 infra-02 coredns: github.com/miekg/dns.(*Server).serveDNS(0xc000122900, 0xc0001ad400, 0x37, 0x200, 0xc0003a8480)
Jul 31 17:35:53 infra-02 coredns: /tmp/tmp.SQtMN80KzX/g/pkg/mod/github.com/miekg/dns@v1.1.15/server.go:609 +0x2e0
Jul 31 17:35:53 infra-02 coredns: github.com/miekg/dns.(*Server).serveUDPPacket(0xc000122900, 0xc00029f504, 0xc0001ad400, 0x37, 0x200, 0xc00000f2d8, 0xc0003a2460)
Jul 31 17:35:53 infra-02 coredns: /tmp/tmp.SQtMN80KzX/g/pkg/mod/github.com/miekg/dns@v1.1.15/server.go:549 +0xb2
Jul 31 17:35:53 infra-02 coredns: created by github.com/miekg/dns.(*Server).serveUDP
Jul 31 17:35:53 infra-02 coredns: /tmp/tmp.SQtMN80KzX/g/pkg/mod/github.com/miekg/dns@v1.1.15/server.go:479 +0x27a
Jul 31 17:35:53 infra-02 systemd: coredns.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 31 17:35:53 infra-02 systemd: Unit coredns.service entered failed state.
Jul 31 17:35:53 infra-02 systemd: coredns.service failed.
Jul 31 17:35:54 infra-02 systemd: coredns.service holdoff time over, scheduling restart.
```

**Comment by dirk-w85** [comment]
Works in Version 1.5.2

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/3071
