### ISSUE TITLE
[ERROR] plugin/errors: 2 me.com. MX: dns: overflow unpacking uint16

### ISSUE THREAD

**Issue by mohatb** [coredns/coredns#3367]
* the version of CoreDNS you are using
1.3.1
* your Corefile
Azure AKS

Corefile:
```                                                                                                                                                         
.:53 {
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      upstream
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
    import custom/*.override
}
```
* logs, if applicable

```
10-10T13:41:50.736Z [INFO] plugin/reload: Running configuration MD5 = d8c69602fc5a3428908dc8f34f9aae58
2019-10-10T13:47:49.441Z [ERROR] plugin/errors: 2 me.com. MX: read udp 10.240.0.13:49706->168.63.129.16:53: i/o timeout
2019-10-10T13:56:33.713Z [ERROR] plugin/errors: 2 me.com. MX: dns: overflow unpacking uint16
2019-10-10T13:58:27.887Z [ERROR] plugin/errors: 2 me.com. MX: dns: overflow unpacking uint16
2019-10-10T14:04:06.415Z [ERROR] plugin/errors: 2 me.com. MX: dns: overflow unpacking uint16
[WARNING] No files matching import glob pattern: custom/*.override
[WARNING] No files matching import glob pattern: custom/*.server
.:53
2019-10-10T13:41:50.776Z [INFO] CoreDNS-1.3.1
2019-10-10T13:41:50.776Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2019-10-10T13:41:50.776Z [INFO] plugin/reload: Running configuration MD5 = d8c69602fc5a3428908dc8f34f9aae58
2019-10-10T13:47:25.505Z [ERROR] plugin/errors: 2 me.com. MX: dns: overflow unpacking uint16
2019-10-10T13:55:07.068Z [ERROR] plugin/errors: 2 me.com. MX: read udp 10.240.0.22:37383->168.63.129.16:53: i/o timeout
2019-10-10T14:04:13.854Z [ERROR] plugin/errors: 2 me.com. MX: read udp 10.240.0.22:41684->168.63.129.16:53: i/o timeout

```

When we are trying to resolve mx records for example:

me.com
icloud.com

using nslookup, we get the below error:

```
root@mynginx-66f8579864-pcqbr:/# nslookup -q=mx icloud.com
Server:         10.0.0.10
Address:        10.0.0.10#53

** server can't find icloud.com: SERVFAIL

root@mynginx-66f8579864-pcqbr:/#

```

- using dig it works fine

```
root@mynginx-66f8579864-pcqbr:/# dig icloud.com mx

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> icloud.com mx
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26680
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 49

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;icloud.com.                    IN      MX

;; ANSWER SECTION:
icloud.com.             30      IN      MX      10 mx5.mail.icloud.com.
icloud.com.             30      IN      MX      10 mx4.mail.icloud.com.
icloud.com.             30      IN      MX      10 mx6.mail.icloud.com.
icloud.com.             30      IN      MX      10 mx3.mail.icloud.com.
icloud.com.             30      IN      MX      10 mx1.mail.icloud.com.
icloud.com.             30      IN      MX      10 mx2.mail.icloud.com.

;; ADDITIONAL SECTION:
mx5.mail.icloud.com.    30      IN      A       17.57.8.138
mx3.mail.icloud.com.    30      IN      A       17.57.8.136
mx5.mail.icloud.com.    30      IN      A       17.133.229.11
mx3.mail.icloud.com.    30      IN      A       17.57.8.141
mx6.mail.icloud.com.    30      IN      A       17.57.8.144
mx2.mail.icloud.com.    30      IN      A       17.178.102.83
mx2.mail.icloud.com.    30      IN      A       17.57.8.140
mx1.mail.icloud.com.    30      IN      A       17.178.102.82
mx6.mail.icloud.com.    30      IN      A       17.172.34.70
mx2.mail.icloud.com.    30      IN      A       17.172.34.11
mx2.mail.icloud.com.    30      IN      A       17.178.102.79
mx2.mail.icloud.com.    30      IN      A       17.142.163.14
mx5.mail.icloud.com.    30      IN      A       17.133.229.13
mx6.mail.icloud.com.    30      IN      A       17.133.229.12
mx5.mail.icloud.com.    30      IN      A       17.178.97.78
mx2.mail.icloud.com.    30      IN      A       17.142.163.11
mx1.mail.icloud.com.    30      IN      A       17.172.34.10
mx2.mail.icloud.com.    30      IN      A       17.57.8.135
mx3.mail.icloud.com.    30      IN      A       17.172.34.65
mx5.mail.icloud.com.    30      IN      A       17.172.34.68
mx1.mail.icloud.com.    30      IN      A       17.57.8.139
mx4.mail.icloud.com.    30      IN      A       17.133.229.9
mx4.mail.icloud.com.    30      IN      A       17.57.8.142
mx1.mail.icloud.com.    30      IN      A       17.142.163.10
mx4.mail.icloud.com.    30      IN      A       17.57.8.137
mx3.mail.icloud.com.    30      IN      A       17.178.97.76
mx3.mail.icloud.com.    30      IN      A       17.178.97.72
mx6.mail.icloud.com.    30      IN      A       17.172.34.71
mx1.mail.icloud.com.    30      IN      A       17.178.102.78
mx1.mail.icloud.com.    30      IN      A       17.57.8.134
mx4.mail.icloud.com.    30      IN      A       17.172.34.66
mx3.mail.icloud.com.    30      IN      A       17.142.163.12
mx4.mail.icloud.com.    30      IN      A       17.133.229.8
mx1.mail.icloud.com.    30      IN      A       17.142.163.13
mx4.mail.icloud.com.    30      IN      A       17.178.97.77
mx6.mail.icloud.com.    30      IN      A       17.133.229.14
mx5.mail.icloud.com.    30      IN      A       17.57.8.143
mx6.mail.icloud.com.    30      IN      A       17.178.97.79
mx5.mail.icloud.com.    30      IN      A       17.178.97.74
mx2.mail.icloud.com.    30      IN      A       17.172.34.12
mx6.mail.icloud.com.    30      IN      A       17.57.8.133
mx4.mail.icloud.com.    30      IN      A       17.172.34.67
mx3.mail.icloud.com.    30      IN      A       17.142.163.15
mx4.mail.icloud.com.    30      IN      A       17.178.97.73
mx6.mail.icloud.com.    30      IN      A       17.178.97.75
mx3.mail.icloud.com.    30      IN      A       17.172.34.64
mx1.mail.icloud.com.    30      IN      A       17.172.34.9
mx5.mail.icloud.com.    30      IN      A       17.172.34.69

;; Query time: 1 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Thu Oct 10 14:44:35 UTC 2019
;; MSG SIZE  rcvd: 932

root@mynginx-66f8579864-pcqbr:/#
```

However, if we immediately after dig command tried nslookup it will work ( I guess this is because it will be cached).

I got a network trace and I can see that both me.com and icloud.com has packet size of 970.

![image](https://user-images.githubusercontent.com/22078761/66579844-2034ff80-eb86-11e9-8f4e-ac2f545842ce.png)

![image](https://user-images.githubusercontent.com/22078761/66579798-0d222f80-eb86-11e9-8991-8da444d5deee.png)

- The issue can be mitigated by adding custom core file with a proxy

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  test.server: |
    me.com:53 {
        errors
        cache 30
        proxy . 8.8.8.8
    }
```

Wondering if this is a bug ? this looks similar to https://github.com/coredns/coredns/issues/2224 but that one seems to be resolved for A records only ?

**Comment by mohatb** [comment]
Hi - Any update on this issue ?

**Comment by chrisohaver** [comment]
`nslookup` uses search domains, whereas `dig` does not by default.  IOW, `nslookup` will first search for `icloud.com.default.svc.cluster.local.`, whereas `dig` will just search for `icloud.com.`.  This means for nslookup, the kubernetes plugin is handling the first MX query sent by the client, and  _should_ return an NXDOMAIN, but there could be a bug there causing it to return SERVFAIL.

Turning on logging in CoreDNS would help see what's going on.

**Comment by chrisohaver** [comment]
Actually nevermind that. Per the errors in the logs (upstream dns timeouts), it seems that we are getting past that part ... IOW, the kubernetes plugin must correctly returning NXDOMAIN, and the forward plugin then times out when the client queries non cluster domains.

**Comment by miekg** [comment]
can't replicate with coredns master branch (1.6.4+ essentially). Corefile:
~~~
.:1053 {
    log
    forward . /etc/resolv.conf
    cache 30
}
~~~
` dig @localhost -p 1053 mx icloud.com  ` returns a correct response.

**Comment by mohatb** [comment]
@chrisohaver yes, it is not just nslookup as I also tested with python and it times out in the logs. However, dig returns good results

**Comment by mohatb** [comment]
any update on this issue ?

**Comment by chrisohaver** [comment]
Have you tried upgrading to CoreDNS 1.6.4?

**Comment by dkmaker** [comment]
@chrisohaver what is the process of upgrade coredns on AKS?

**Comment by chrisohaver** [comment]
@zenturacp, I don't have hands-on experience with AKS.  But generally, the process is to update the coredns Deployment to point to the newer image.  There are occasional plugin/option config deprecations between versions, so the Corefile might need to be adjusted case by case.  The most common one is that the _proxy_ plugin must be replaced by the _forward_ plugin (`s/proxy/forward/`).  If AKS doesn't allow you to edit the Deployment directly, then they should have documented somewhere how to get around that.

**Comment by mohatb** [comment]
Hi @chrisohaver - I tested with AKS running coredns 1.6.4 and still the same issue:

![image](https://user-images.githubusercontent.com/22078761/68660530-05b5c380-0542-11ea-9d4c-5bd43ff1b3f5.png)

```
root@mynginx-6b7b7bcd75-rzcvq:/# nslookup
> me.com
Server:         10.0.0.10
Address:        10.0.0.10#53

Non-authoritative answer:
Name:   me.com
Address: 17.142.160.83
Name:   me.com
Address: 17.172.224.103
Name:   me.com
Address: 17.178.96.97
> set type=mx
> me.com
Server:         10.0.0.10
Address:        10.0.0.10#53

** server can't find me.com: SERVFAIL
>
```




![image](https://user-images.githubusercontent.com/22078761/68660630-3564cb80-0542-11ea-8de0-ffbff67b356e.png)

I am also using official image coredns/coredns:1.6.4

**Comment by chrisohaver** [comment]
Try ....

* an MX look up with dig: `dig -t MX me.com`
* an MX look up with dig directly against the upstream server: `dig @168.63.129.16 -t MX me.com`

**Comment by chrisohaver** [comment]
And ...
* an MX lookup with nslookup directly against the upstream server

**Comment by chrisohaver** [comment]
And also try an MX lookup with nslookup using a fully qualified domain name `me.com.` (note the trailing dot.)

**Comment by mohatb** [comment]
Hi @chrisohaver - Yes, as I mentioned on the initial issue description. dig, and query against upstream directly both works fine. Even using nslookup with vc "force tcp" also works fine. mainly if we are using UDP with payload larger than 512 it fails.

It is not limited to only nslookup tool, but I also tested with python http://www.dnspython.org/examples.html and it fails as well.

```
>>> result = dns.resolver.query('me.com', 'MX')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 1102, in query
lifetime)
File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 992, in query
timeout = self._compute_timeout(start, lifetime)
File "/usr/local/lib/python2.7/dist-packages/dns/resolver.py", line 799, in _compute_timeout
raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 30.0012218952 seconds
```

Using nslookup with vc
```
root@nginx-example-6cdd6bf4c5-bpl2d:/# nslookup
> set type=mx
> icloud.com
Server:         10.0.0.10
Address:        10.0.0.10#53

** server can't find icloud.com: SERVFAIL
> set vc
> icloud.com
Server:         10.0.0.10
Address:        10.0.0.10#53

Non-authoritative answer:
icloud.com      mail exchanger = 10 mx4.mail.icloud.com.
icloud.com      mail exchanger = 10 mx2.mail.icloud.com.
icloud.com      mail exchanger = 10 mx6.mail.icloud.com.
icloud.com      mail exchanger = 10 mx3.mail.icloud.com.
icloud.com      mail exchanger = 10 mx1.mail.icloud.com.
icloud.com      mail exchanger = 10 mx5.mail.icloud.com.

Authoritative answers can be found from:
mx2.mail.icloud.com     internet address = 17.142.163.11
mx1.mail.icloud.com     internet address = 17.57.8.134
mx3.mail.icloud.com     internet address = 17.142.163.12
mx5.mail.icloud.com     internet address = 17.172.34.68
mx2.mail.icloud.com     internet address = 17.57.8.135
mx3.mail.icloud.com     internet address = 17.178.97.72
mx4.mail.icloud.com     internet address = 17.178.97.77
mx5.mail.icloud.com     internet address = 17.172.34.69
mx3.mail.icloud.com     internet address = 17.172.34.64
mx2.mail.icloud.com     internet address = 17.172.34.11
mx6.mail.icloud.com     internet address = 17.172.34.71
mx6.mail.icloud.com     internet address = 17.178.97.79
mx6.mail.icloud.com     internet address = 17.57.8.133
mx2.mail.icloud.com     internet address = 17.178.102.79
mx4.mail.icloud.com     internet address = 17.133.229.8
mx1.mail.icloud.com     internet address = 17.178.102.82
mx2.mail.icloud.com     internet address = 17.172.34.12
mx6.mail.icloud.com     internet address = 17.133.229.14
mx1.mail.icloud.com     internet address = 17.172.34.9
mx1.mail.icloud.com     internet address = 17.172.34.10
mx6.mail.icloud.com     internet address = 17.172.34.70
mx4.mail.icloud.com     internet address = 17.172.34.67
mx4.mail.icloud.com     internet address = 17.172.34.66
mx4.mail.icloud.com     internet address = 17.57.8.137
mx1.mail.icloud.com     internet address = 17.178.102.78
mx3.mail.icloud.com     internet address = 17.57.8.136
mx3.mail.icloud.com     internet address = 17.172.34.65
mx6.mail.icloud.com     internet address = 17.133.229.12
mx5.mail.icloud.com     internet address = 17.178.97.74
mx5.mail.icloud.com     internet address = 17.57.8.143
mx3.mail.icloud.com     internet address = 17.142.163.15
mx2.mail.icloud.com     internet address = 17.142.163.14
mx3.mail.icloud.com     internet address = 17.178.97.76
mx4.mail.icloud.com     internet address = 17.178.97.73
mx1.mail.icloud.com     internet address = 17.142.163.13
mx6.mail.icloud.com     internet address = 17.178.97.75
mx4.mail.icloud.com     internet address = 17.133.229.9
mx3.mail.icloud.com     internet address = 17.57.8.141
mx2.mail.icloud.com     internet address = 17.57.8.140
mx5.mail.icloud.com     internet address = 17.57.8.138
mx5.mail.icloud.com     internet address = 17.133.229.11
mx6.mail.icloud.com     internet address = 17.57.8.144
mx1.mail.icloud.com     internet address = 17.142.163.10
mx2.mail.icloud.com     internet address = 17.178.102.83
mx5.mail.icloud.com     internet address = 17.133.229.13
mx1.mail.icloud.com     internet address = 17.57.8.139
mx4.mail.icloud.com     internet address = 17.57.8.142
mx5.mail.icloud.com     internet address = 17.178.97.78
> me.com
Server:         10.0.0.10
Address:        10.0.0.10#53

Non-authoritative answer:
me.com  mail exchanger = 10 mx4.mail.icloud.com.
me.com  mail exchanger = 10 mx5.mail.icloud.com.
me.com  mail exchanger = 10 mx1.mail.icloud.com.
me.com  mail exchanger = 10 mx2.mail.icloud.com.
me.com  mail exchanger = 10 mx3.mail.icloud.com.
me.com  mail exchanger = 10 mx6.mail.icloud.com.

Authoritative answers can be found from:
mx2.mail.icloud.com     internet address = 17.172.34.12
mx1.mail.icloud.com     internet address = 17.178.102.82
mx5.mail.icloud.com     internet address = 17.57.8.138
mx5.mail.icloud.com     internet address = 17.178.97.74
mx3.mail.icloud.com     internet address = 17.172.34.64
mx3.mail.icloud.com     internet address = 17.178.97.72
mx4.mail.icloud.com     internet address = 17.178.97.77
mx2.mail.icloud.com     internet address = 17.142.163.11
mx1.mail.icloud.com     internet address = 17.142.163.13
mx1.mail.icloud.com     internet address = 17.57.8.139
mx4.mail.icloud.com     internet address = 17.172.34.67
mx5.mail.icloud.com     internet address = 17.172.34.68
mx4.mail.icloud.com     internet address = 17.178.97.73
mx1.mail.icloud.com     internet address = 17.172.34.9
mx5.mail.icloud.com     internet address = 17.178.97.78
mx2.mail.icloud.com     internet address = 17.172.34.11
mx4.mail.icloud.com     internet address = 17.57.8.137
mx5.mail.icloud.com     internet address = 17.133.229.13
mx2.mail.icloud.com     internet address = 17.178.102.79
mx2.mail.icloud.com     internet address = 17.57.8.135
mx1.mail.icloud.com     internet address = 17.178.102.78
mx3.mail.icloud.com     internet address = 17.57.8.136
mx6.mail.icloud.com     internet address = 17.178.97.79
mx2.mail.icloud.com     internet address = 17.57.8.140
mx1.mail.icloud.com     internet address = 17.172.34.10
mx4.mail.icloud.com     internet address = 17.133.229.9
mx2.mail.icloud.com     internet address = 17.142.163.14
mx4.mail.icloud.com     internet address = 17.57.8.142
mx6.mail.icloud.com     internet address = 17.133.229.14
mx4.mail.icloud.com     internet address = 17.172.34.66
mx6.mail.icloud.com     internet address = 17.133.229.12
mx3.mail.icloud.com     internet address = 17.142.163.15
mx3.mail.icloud.com     internet address = 17.142.163.12
mx6.mail.icloud.com     internet address = 17.57.8.144
mx5.mail.icloud.com     internet address = 17.172.34.69
mx4.mail.icloud.com     internet address = 17.133.229.8
mx6.mail.icloud.com     internet address = 17.57.8.133
mx3.mail.icloud.com     internet address = 17.57.8.141
mx6.mail.icloud.com     internet address = 17.172.34.70
mx6.mail.icloud.com     internet address = 17.172.34.71
mx6.mail.icloud.com     internet address = 17.178.97.75
mx3.mail.icloud.com     internet address = 17.178.97.76
mx5.mail.icloud.com     internet address = 17.57.8.143
mx3.mail.icloud.com     internet address = 17.172.34.65
mx5.mail.icloud.com     internet address = 17.133.229.11
mx2.mail.icloud.com     internet address = 17.178.102.83
mx1.mail.icloud.com     internet address = 17.142.163.10
mx1.mail.icloud.com     internet address = 17.57.8.134
```

**Comment by mohatb** [comment]
also - it works fine when the domain is cached. for example, run the query using dig and immediately after that run it in nslookup.

**Comment by mohatb** [comment]
using FQDN me.com. also failes.

```
root@mynginx-6b7b7bcd75-2qqqb:/# nslookup
> set type=mx
> me.com
Server:         10.0.0.10
Address:        10.0.0.10#53

** server can't find me.com: SERVFAIL
> me.com.
Server:         10.0.0.10
Address:        10.0.0.10#53

** server can't find me.com: SERVFAIL
>
```

**Comment by mohatb** [comment]
I also tested in minikube using coredns 1.3.1 and it is also failing but sometimes it works:

```
PS C:\WINDOWS\system32> kubectl logs coredns-fb8b8dccf-td5x5 -n kube-system
.:53
2019-11-12T22:20:25.204Z [INFO] CoreDNS-1.3.1
2019-11-12T22:20:25.204Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2019-11-12T22:20:25.204Z [INFO] plugin/reload: Running configuration MD5 = 599b9eb76b8c147408aed6a0bbe0f669
2019-11-12T22:29:59.401Z [ERROR] plugin/errors: 2 me.com. MX: read udp 172.17.0.2:53408->208.67.222.222:53: i/o timeout
PS C:\WINDOWS\system32>
```

**Comment by chrisohaver** [comment]
> Yes, _as I mentioned on the initial issue description_. dig, and query against upstream directly both works fine.

You only mention testing against CoreDNS that I can see ... not directly against the upstream dns server. 

To verify: You have tested nslookup for me.com MX record directly to your upstream server (168.63.129.16)? And it works?

**Comment by mohatb** [comment]
Hi Chris - sorry, I think I mentioned it somewhere else. yes, you can see the results working fine for both nslookup and dig when direct to upstream dns.

```
root@my-bash:/# dig @168.63.129.16 -t MX me.com

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> @168.63.129.16 -t MX me.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58062
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 49

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;me.com.                                IN      MX

;; ANSWER SECTION:
me.com.                 300     IN      MX      10 mx1.mail.icloud.com.
me.com.                 300     IN      MX      10 mx2.mail.icloud.com.
me.com.                 300     IN      MX      10 mx3.mail.icloud.com.
me.com.                 300     IN      MX      10 mx4.mail.icloud.com.
me.com.                 300     IN      MX      10 mx5.mail.icloud.com.
me.com.                 300     IN      MX      10 mx6.mail.icloud.com.

;; ADDITIONAL SECTION:
mx1.mail.icloud.com.    6       IN      A       17.142.163.10
mx1.mail.icloud.com.    6       IN      A       17.142.163.13
mx1.mail.icloud.com.    6       IN      A       17.57.8.139
mx1.mail.icloud.com.    6       IN      A       17.57.8.134
mx1.mail.icloud.com.    6       IN      A       17.172.34.9
mx1.mail.icloud.com.    6       IN      A       17.172.34.10
mx1.mail.icloud.com.    6       IN      A       17.178.102.78
mx1.mail.icloud.com.    6       IN      A       17.178.102.82
mx2.mail.icloud.com.    6       IN      A       17.142.163.11
mx2.mail.icloud.com.    6       IN      A       17.142.163.14
mx2.mail.icloud.com.    6       IN      A       17.57.8.135
mx2.mail.icloud.com.    6       IN      A       17.57.8.140
mx2.mail.icloud.com.    6       IN      A       17.172.34.11
mx2.mail.icloud.com.    6       IN      A       17.172.34.12
mx2.mail.icloud.com.    6       IN      A       17.178.102.83
mx2.mail.icloud.com.    6       IN      A       17.178.102.79
mx3.mail.icloud.com.    6       IN      A       17.178.97.72
mx3.mail.icloud.com.    6       IN      A       17.178.97.76
mx3.mail.icloud.com.    6       IN      A       17.57.8.136
mx3.mail.icloud.com.    6       IN      A       17.57.8.141
mx3.mail.icloud.com.    6       IN      A       17.172.34.64
mx3.mail.icloud.com.    6       IN      A       17.172.34.65
mx3.mail.icloud.com.    6       IN      A       17.142.163.15
mx3.mail.icloud.com.    6       IN      A       17.142.163.12
mx4.mail.icloud.com.    6       IN      A       17.178.97.73
mx4.mail.icloud.com.    6       IN      A       17.178.97.77
mx4.mail.icloud.com.    6       IN      A       17.57.8.137
mx4.mail.icloud.com.    6       IN      A       17.57.8.142
mx4.mail.icloud.com.    6       IN      A       17.172.34.66
mx4.mail.icloud.com.    6       IN      A       17.172.34.67
mx4.mail.icloud.com.    6       IN      A       17.133.229.9
mx4.mail.icloud.com.    6       IN      A       17.133.229.8
mx5.mail.icloud.com.    6       IN      A       17.178.97.78
mx5.mail.icloud.com.    6       IN      A       17.178.97.74
mx5.mail.icloud.com.    6       IN      A       17.57.8.143
mx5.mail.icloud.com.    6       IN      A       17.57.8.138
mx5.mail.icloud.com.    6       IN      A       17.172.34.68
mx5.mail.icloud.com.    6       IN      A       17.172.34.69
mx5.mail.icloud.com.    6       IN      A       17.133.229.13
mx5.mail.icloud.com.    6       IN      A       17.133.229.11
mx6.mail.icloud.com.    6       IN      A       17.178.97.75
mx6.mail.icloud.com.    6       IN      A       17.178.97.79
mx6.mail.icloud.com.    6       IN      A       17.57.8.133
mx6.mail.icloud.com.    6       IN      A       17.57.8.144
mx6.mail.icloud.com.    6       IN      A       17.172.34.70
mx6.mail.icloud.com.    6       IN      A       17.172.34.71
mx6.mail.icloud.com.    6       IN      A       17.133.229.12
mx6.mail.icloud.com.    6       IN      A       17.133.229.14

;; Query time: 5 msec
;; SERVER: 168.63.129.16#53(168.63.129.16)
;; WHEN: Sun Dec 08 13:16:00 UTC 2019
;; MSG SIZE  rcvd: 935

root@my-bash:/#                                            
```


Same with nslookup

```
root@my-bash:/# nslookup
> set type=mx
> server 168.63.129.16
Default server: 168.63.129.16
Address: 168.63.129.16#53
> me.com
Server:         168.63.129.16
Address:        168.63.129.16#53

Non-authoritative answer:
me.com  mail exchanger = 10 mx2.mail.icloud.com.
me.com  mail exchanger = 10 mx3.mail.icloud.com.
me.com  mail exchanger = 10 mx4.mail.icloud.com.
me.com  mail exchanger = 10 mx5.mail.icloud.com.
me.com  mail exchanger = 10 mx6.mail.icloud.com.
me.com  mail exchanger = 10 mx1.mail.icloud.com.

Authoritative answers can be found from:
mx2.mail.icloud.com     internet address = 17.172.34.12
mx2.mail.icloud.com     internet address = 17.178.102.83
mx2.mail.icloud.com     internet address = 17.178.102.79
mx2.mail.icloud.com     internet address = 17.142.163.11
mx2.mail.icloud.com     internet address = 17.142.163.14
mx2.mail.icloud.com     internet address = 17.57.8.135
mx2.mail.icloud.com     internet address = 17.57.8.140
mx2.mail.icloud.com     internet address = 17.172.34.11
mx3.mail.icloud.com     internet address = 17.57.8.141
mx3.mail.icloud.com     internet address = 17.142.163.12
mx3.mail.icloud.com     internet address = 17.142.163.15
mx3.mail.icloud.com     internet address = 17.172.34.64
mx3.mail.icloud.com     internet address = 17.172.34.65
mx3.mail.icloud.com     internet address = 17.178.97.72
mx3.mail.icloud.com     internet address = 17.178.97.76
mx3.mail.icloud.com     internet address = 17.57.8.136
mx4.mail.icloud.com     internet address = 17.172.34.67
mx4.mail.icloud.com     internet address = 17.133.229.9
mx4.mail.icloud.com     internet address = 17.133.229.8
mx4.mail.icloud.com     internet address = 17.178.97.73
mx4.mail.icloud.com     internet address = 17.178.97.77
mx4.mail.icloud.com     internet address = 17.57.8.137
mx4.mail.icloud.com     internet address = 17.57.8.142
mx4.mail.icloud.com     internet address = 17.172.34.66
mx5.mail.icloud.com     internet address = 17.172.34.69
mx5.mail.icloud.com     internet address = 17.133.229.13
mx5.mail.icloud.com     internet address = 17.133.229.11
mx5.mail.icloud.com     internet address = 17.178.97.78
mx5.mail.icloud.com     internet address = 17.178.97.74
mx5.mail.icloud.com     internet address = 17.57.8.143
mx5.mail.icloud.com     internet address = 17.57.8.138
mx5.mail.icloud.com     internet address = 17.172.34.68
mx6.mail.icloud.com     internet address = 17.57.8.144
mx6.mail.icloud.com     internet address = 17.133.229.12
mx6.mail.icloud.com     internet address = 17.133.229.14
mx6.mail.icloud.com     internet address = 17.172.34.70
mx6.mail.icloud.com     internet address = 17.172.34.71
mx6.mail.icloud.com     internet address = 17.178.97.75
mx6.mail.icloud.com     internet address = 17.178.97.79
mx6.mail.icloud.com     internet address = 17.57.8.133
mx1.mail.icloud.com     internet address = 17.57.8.139
mx1.mail.icloud.com     internet address = 17.142.163.10
mx1.mail.icloud.com     internet address = 17.142.163.13
mx1.mail.icloud.com     internet address = 17.172.34.9
mx1.mail.icloud.com     internet address = 17.172.34.10
mx1.mail.icloud.com     internet address = 17.178.102.78
mx1.mail.icloud.com     internet address = 17.178.102.82
mx1.mail.icloud.com     internet address = 17.57.8.134
>
```

**Comment by greenpau** [comment]
@mohatb , a few questions:
* What is the content of `resolv.conf` of `mynginx-66f8579864-pcqbr`? (looked in the thread; but did not find it)
* What is the OS of `mynginx-66f8579864-pcqbr`?
* If there is `strace` on that box (or similar tool), please run `nslookup` with it.

Also, FYI, here are some relevant threads on the subject:
* https://github.com/Azure/AKS/issues/1320
* https://github.com/Azure/AKS/issues/1326

Have you tried the below?

> A workaround has been to set dnsPolicy: Default, however with the dns policy set to ClusterFirst this is definitely able to be reproduced on 1.13.12.

**Comment by chrisohaver** [comment]
> you can see the results working fine for both nslookup and dig when direct to upstream dns.

This means that CoreDNS is almost certainly the culprit.  Perhaps it is constructing the query to the upstream differently than the client is, or doing something to the response before relaying it to the client.  I'm not deeply familiar with the mechanisms of _forward_.  But I imagine seeing packet captures of the request and response would help pinpoint how _forward_ is involved in producing this result...
1. the request: before it reaches CoreDNS
2. the request: after it leaves CoreDNS on route to the upstream
3. the response: from the upstream before it reaches CoreDNS
4. the response: from CoreDNS to the client

**Comment by mohatb** [comment]
Hi @chrisohaver 

I can provide a tcpdump capture from the nodes and the pods, would that be enough? I am not sure if I can capture from inside coredns pods as it does not allow exec

**Comment by pniederlag** [comment]
we are also seeing a i/o timeout in AKS for MX lookup on me.com, using aksrepos.azurecr.io/mirror/coredns:1.2.6 symptoms are much like described here, but no explicit "overflow unpacking" error message. Any suggestions for a workaround?

**Comment by mossad-zika** [comment]
why this ticket is closed ?
