### ISSUE TITLE
java.net.UnknownHostException

### ISSUE THREAD

**Issue by niuqg** [coredns/coredns#3819]
**What happened**:
java error stack
```
Caused by: java.net.UnknownHostException:  foo.bar.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[?:1.8.0_211]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_211]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_211]
	at java.net.InetAddress.getByName(InetAddress.java:1077) ~[?:1.8.0_211]
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146) ~[netty-common-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143) ~[netty-common-4.1.28.Final.jar:4.1.28.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143) ~[netty-common-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43) ~[netty-resolver-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63) ~[netty-resolver-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55) ~[netty-resolver-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57) ~[netty-resolver-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32) ~[netty-resolver-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108) ~[netty-resolver-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208) ~[netty-transport-4.1.28.Final.jar:4.1.28.Final]
	... 18 more
```

**Anything else we need to know?**:
Coredns logs only two requests
```
"A IN foo.bar.com.kube-system.svc.cluster.local. udp 104 false 512  NXDOMAIN
"A IN foo.bar.com.svc.cluster.local. udp 80 false 512" NXDOMAIN
```
Normally there should be two more request logs，like this
```
"A IN foo.bar.com.cluster.local. udp 104 false 512  NXDOMAIN
"A IN foo.bar.com. udp 80 false 512" NOERROR
```
I don’t know if the lost DNS request is due to coredns or other

**Environment**:

- the version of CoreDNS: 1.2.6
- Corefile:
```
   .:53 {
        log
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           upstream
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```
- the version of kubernetes: 1.13.5
- the backend of flanneld: host-gw
- OS (e.g: `cat /etc/os-release`):  CentOS Linux release 7.2.1511 (Core)

**Comment by stp-ip** [comment]
Assumption without more details is that the request never hit CoreDNS as the log doesn't show the requests being hit. Therefore it is most likely the network or the pod being down.

Without more details, that show the requests actually hit CoreDNS we can't do much.
Closing this for now, happy for you to reopen with more details, if it's not the network.

/label kubernetes
/close

**Comment by chrisohaver** [comment]
> Assumption without more details is that the request never hit CoreDNS as the log doesn't show the requests being hit.

Technically speaking, IIRC, CoreDNS doesn't log _request_ hits, it logs _responses_.  Although unlikely here, it is possible for CoreDNS to receive a request, not respond, and therefore log nothing.

@niuqg make sure you are checking logs of all coredns Pods. Most deployment default to 2 instances.

**Comment by stp-ip** [comment]
> Technically speaking, IIRC, CoreDNS doesn't log _request_ hits, it logs _responses_. Although unlikely here, it is possible for CoreDNS to receive a request, not respond, and therefore log nothing.

Valid. Should have made that clearer. Thanks for jumping in.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] java.net.Unkn..." ]
>    Technically speaking, IIRC, CoreDNS doesn't log request hits, it logs
>    responses. Although unlikely here, it is possible for CoreDNS to receive a
>    request, not respond, and therefore log nothing.
>
>Valid. Should have made that clearer. Thanks for jumping in.

If you need that (log requests) you can use github.com/miekg/dump (if it still compiles)

/Miek

--
Miek Gieben

**Comment by niuqg** [comment]
> > Assumption without more details is that the request never hit CoreDNS as the log doesn't show the requests being hit.
> 
> Technically speaking, IIRC, CoreDNS doesn't log _request_ hits, it logs _responses_. Although unlikely here, it is possible for CoreDNS to receive a request, not respond, and therefore log nothing.
> 
> @niuqg make sure you are checking logs of all coredns Pods. Most deployment default to 2 instances.

I have checked logs of all coredns Pods. I'm using tcpdump to determine if there is packet loss. Maybe some reason like this [Racy conntrack and DNS lookup timeouts](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts)
