### ISSUE TITLE
plugin/grpc: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by milgradesec** [coredns/coredns#4047]
CoreDNS crashed with segmentation fault.

- the version of CoreDNS:

CoreDNS-1.7.0,
linux/arm64, go1.15beta1, v1.7.0

- Corefile:

```
tls://.:8530 https://.:8080 dns://.:5353 {
    cancel
    ratelimit 80
    any
    grpc . 127.0.0.1:5300
}

grpc://.:5300 {
    cache {
        success 10000
        denial 5000
        serve_stale
    }
    hosts /etc/Coredns/hosts {
        fallthrough
    }
    filter {
        allow /lists/allowlist.list
        block /lists/denylist.list 
        block /lists/blocklist.list
        uncloak
    }
    grpc . 127.0.0.1:5301
}

grpc://.:5301 {
    forward . tls://1.0.0.2 {
        tls_servername cloudflare-dns.com
        health_check 5s
    }
}
```
- logs, if applicable:

```
panic: runtime error: invalid memory address or nil pointer dereference,
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x32347c],
,
goroutine 275047 [running]:,
github.com/miekg/dns.(*OPT).len(0x40003cf940, 0x29, 0x0, 0x0),
	/go/pkg/mod/github.com/miekg/dns@v1.1.30/edns.go:85 +0x9c,
github.com/miekg/dns.msgLenWithCompressionMap(0x40004cba70, 0x0, 0x4001f664e8),
	/go/pkg/mod/github.com/miekg/dns@v1.1.30/msg.go:970 +0x110,
github.com/miekg/dns.(*Msg).packBufferWithCompressionMap(0x40004cba70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4001f66600, 0x6febb0, 0x5f2c8a1d, 0x9cfcf21, ...),
	/go/pkg/mod/github.com/miekg/dns@v1.1.30/msg.go:782 +0x148,
github.com/miekg/dns.(*Msg).PackBuffer(0x40004cba70, 0x0, 0x0, 0x0, 0x106b278, 0x0, 0x0, 0x6fe13c, 0x4001f66688),
	/go/pkg/mod/github.com/miekg/dns@v1.1.30/msg.go:728 +0xf0,
github.com/miekg/dns.(*Msg).Pack(...),
	/go/pkg/mod/github.com/miekg/dns@v1.1.30/msg.go:716,
github.com/coredns/coredns/plugin/grpc.(*Proxy).query(0x4000b38c00, 0xac56e0, 0x400156afc0, 0x40004cba70, 0x1419b6c3c6411, 0x1039da0, 0x1039d01),
	/go/src/app/coredns/plugin/grpc/proxy.go:52 +0x50,
github.com/coredns/coredns/plugin/grpc.(*GRPC).ServeDNS(0x4000b43480, 0xac56e0, 0x400156afc0, 0xad0020, 0x4000bd0160, 0x40004cba70, 0x963980, 0x0, 0x4001f669a8),
	/go/src/app/coredns/plugin/grpc/grpc.go:66 +0x1f0,
github.com/coredns/coredns/plugin.NextOrFailure(0x9a761d, 0x5, 0xab79e0, 0x4000b43480, 0xac56e0, 0x400156afc0, 0xad0020, 0x4000bd0160, 0x40004cba70, 0x0, ...),
	/go/src/app/coredns/plugin/plugin.go:80 +0xa4,
github.com/coredns/coredns/plugin/hosts.Hosts.ServeDNS(0xab79e0, 0x4000b43480, 0x4000b42280, 0x40002352f0, 0x1, 0x1, 0xac56e0, 0x400156afc0, 0xad0020, 0x4000bd0160, ...),
	/go/src/app/coredns/plugin/hosts/hosts.go:58 +0x1a4,
github.com/coredns/coredns/plugin.NextOrFailure(0x9a8616, 0x6, 0xaba2e0, 0x400116fe60, 0xac56e0, 0x400156afc0, 0xad0020, 0x4000bd0160, 0x40004cba70, 0x0, ...),
	/go/src/app/coredns/plugin/plugin.go:80 +0xa4,
github.com/milgradesec/filter.(*Filter).ServeDNS(0x4000b38880, 0xac56e0, 0x400156afc0, 0xace040, 0x4000dcc6c0, 0x40004cba70, 0x4001ff6d01, 0x4000fbd300, 0x40006e0e00),
	/go/pkg/mod/github.com/milgradesec/filter@v0.0.0-20200720023556-912729e3a00e/filter.go:57 +0x1b0,
github.com/coredns/coredns/plugin.NextOrFailure(0x9a7415, 0x5, 0xab7c20, 0x4000b38880, 0xac56e0, 0x400156afc0, 0xace040, 0x4000dcc6c0, 0x40004cba70, 0x0, ...),
	/go/src/app/coredns/plugin/plugin.go:80 +0xa4,
github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS.func1(0x4000f01680, 0x40001a73b0, 0x40012b5100, 0x40002b8e50, 0xc, 0xace3a0, 0x4001182300, 0xac56e0, 0x400156afc0),
	/go/src/app/coredns/plugin/cache/handler.go:44 +0x144,
created by github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS,
/go/src/app/coredns/plugin/cache/handler.go:41 +0x454,
```

- OS (e.g: `cat /etc/os-release`):

Ubuntu 20.04.1 LTS (Focal Fossa)

- Others:

_filter_ plugin at github.com/milgradesec/filter

**Comment by miekg** [comment]
seems something is returning a ni lmsg somewhere, as filter is not a default plugin I will not further debug. what's the minimal corefile this shows up with?

**Comment by milgradesec** [comment]
i dont know it only happened once, the request passed to hosts plugin so filter did nothing

**Comment by zouyee** [comment]
```
func (rr *OPT) len(off int, compression map[string]struct{}) int {
	l := rr.Hdr.len(off, compression)
	for _, o := range rr.Option {
		l += 4 // Account for 2-byte option code and 2-byte option length.
		lo, _ := o.pack()
		l += len(lo)
	}
	return l
}
```
The reason for panic is that the `len` function is used without null pointer check on the result.

Because I don’t know where the `ratelimit` plugin is, I only added the `filter` plugin, but the problem has not been reproduced.
/cc @miekg

**Comment by milgradesec** [comment]
The `ratelimit`  plugin is at github.com/milgradesec/ratelimit

**Comment by zouyee** [comment]
Could you provide reproduce steps?

**Comment by milgradesec** [comment]
I found a container crashed with that error but no idea what triggered it, only happened once so I can't provide more

**Comment by pguinardco** [comment]
I'm able to reproduce over and over in two of our test environments but am not able to reproduce it in a second environment running the same query load.

Here's our core file that works and does reproduce this error:

```
    .:53 {
        cache {
          serve_stale
        }
        errors
        forward . /etc/resolv.conf
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          upstream
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        health
        loadbalance
        prometheus :9153
    }
```

And this suceeds

```
Here's our core file that works and does reproduce this error:

```
    .:53 {
        cache
        errors
        forward . /etc/resolv.conf
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          upstream
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        health
        loadbalance
        prometheus :9153
    }
```

Unfortunately in the environments that I can reproduce this in, I can't get much less in this core file.

When querying all of these records in a lower environment, I'm not able to reproduce this.

This exists on 1.6.7 through 1.7.0.

I have not been able to reproduce this outside of kubernetes as well. Trying to reproduce at this point.

EDIT:

I've split some of our zones out into different files and have tracked this back to the kubernetes plugin for our use case.

**Comment by miekg** [comment]
This should not be called with a nil msg. Still waiting for a smaller repro
