### ISSUE TITLE
atomic.AddUint64 in 32-bit cause panic

### ISSUE THREAD

**Issue by zouyee** [coredns/coredns#4111]
**What happened**:
atomic.AddUint64 in 32-bit cause panic
```
[INFO] plugin/reload: Running configuration MD5 = 1ea4ac40c2a2283a62381a66c976f90b
CoreDNS-1.7.0
linux/386, go1.14.4,
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x80524bc]
goroutine 72 [running]:
runtime/internal/atomic.Xadd64(0xb8abd9c, 0x1, 0x0, 0x0, 0xc)
	/usr/local/go/src/runtime/internal/atomic/asm_386.s:105 +0xc
github.com/coredns/coredns/plugin/trace.(*trace).ServeDNS(0xb8abd60, 0x9965cc0, 0xba29380, 0x9970c20, 0xb89ffa0, 0xba2a410, 0x0, 0x0, 0x0)
	/root/coredns/plugin/trace/trace.go:85 +0x4a4
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS(0xbc384c0, 0x9965cc0, 0xba29380, 0x9970c20, 0xb89ffa0, 0xba2a410)
	/root/coredns/core/dnsserver/server.go:285 +0x361
github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1(0x9971ee0, 0xb881e30, 0xba2a410)
	/root/coredns/core/dnsserver/server.go:126 +0x8a
github.com/miekg/dns.HandlerFunc.ServeDNS(0xb811008, 0x9971ee0, 0xb881e30, 0xba2a410)
	/dcos/gopath/pkg/mod/github.com/miekg/dns@v1.1.31/server.go:37 +0x34
github.com/miekg/dns.(*Server).serveDNS(0xb8ac6e0, 0xb90e200, 0x25, 0x200, 0xb881e30)
	/dcos/gopath/pkg/mod/github.com/miekg/dns@v1.1.31/server.go:609 +0x258
github.com/miekg/dns.(*Server).serveUDPPacket(0xb8ac6e0, 0xbc09a10, 0xb90e200, 0x25, 0x200, 0xb810d80, 0xb89fec0)
	/dcos/gopath/pkg/mod/github.com/miekg/dns@v1.1.31/server.go:549 +0x92
created by github.com/miekg/dns.(*Server).serveUDP
	/dcos/gopath/pkg/mod/github.com/miekg/dns@v1.1.31/server.go:479 +0x1f4
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
`GOARCH=386 go run coredns.go`

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: latest
- Corefile:
```
.:53 {
        errors
	debug
	log
        health {
           lameduck 5s
        }
        ready
	trace localhost:9411 {
	   every 10000
	   service dnsproxy
	}
        cache 30
        loop
        reload
        loadbalance
    }
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): Linux elk-141 4.9.6-200.2.el7.xxx.x86_64 #1 SMP Wed Mar 1 18:39:23 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by zouyee** [comment]
Similar questions: https://github.com/rs/zerolog/issues/228
Reason: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
Possible solution： https://github.com/rs/zerolog/pull/229
or just changing `count`  to an uint32 instead

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] atomic.AddUin..." ]
>Similar questions: rs/zerolog#228
>Reason: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
>Possible solution： rs/zerolog#229
>or just changing count to an uint32 instead

the struct alignment is wrong, see #4112
