### ISSUE TITLE
coredns pods memory leak

### ISSUE THREAD

**Issue by amit-handda** [coredns/coredns#4278]
**What happened**:
coredns pods memory consumption increases slowly but steadily (~ 2.5MB/30 minutes approx), in a cluster not having much activity.
It happens once we upgrade/rolling-restart cluster nodes (master, worker).

**What you expected to happen**:
coredns pods memory consumption should have remained stable.

**How to reproduce it (as minimally and precisely as possible)**:
Its not consistent. we reproduced it on 30% of our clusters. 

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.6.9
- Corefile:
```
    .:53 {
        bind 192.168.0.1
        errors
        health :8081 {
          lameduck 5s
        }
        kubernetes cluster.local. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        loop
        cache 30
        loadbalance
        reload
    }
```

- logs, if applicable:

```
❯ k logs  -n infra-system coredns-ds-5vgtg
.:53 on 192.168.0.1
prod.ddsd.:53 on 192.168.0.1
[INFO] plugin/reload: Running configuration MD5 = b1165553b8969f4c67c0a027202b371f
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568
W1110 16:57:57.879333       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 172.30.18.62:60710->172.30.224.1:443: read: connection timed out") has prevented the request from succeeding
W1110 16:57:57.879333       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: watch of *v1.Namespace ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 172.30.18.62:60710->172.30.224.1:443: read: connection timed out") has prevented the request from succeeding
W1110 16:57:57.879334       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: watch of *v1.Endpoints ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 172.30.18.62:60710->172.30.224.1:443: read: connection timed out") has prevented the request from succeeding
W1110 17:12:24.172880       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: watch of *v1.Namespace ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 172.30.18.62:17212->172.30.224.1:443: read: connection timed out") has prevented the request from succeeding
W1110 17:12:24.172881       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: watch of *v1.Service ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 172.30.18.62:17212->172.30.224.1:443: read: connection timed out") has prevented the request from succeeding
W1110 17:12:24.172881       1 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: watch of *v1.Endpoints ended with: an error on the server ("unable to decode an event from the watch stream: read tcp 172.30.18.62:17212->172.30.224.1:443: read: connection timed out") has prevented the request from succeeding
E1110 17:12:25.186860       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 87 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x194e000, 0x2cdd240)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:48 +0x82
panic(0x194e000, 0x2cdd240)
	/tmp/tmp.BwnuHrciKQ/go/src/runtime/panic.go:967 +0x166
github.com/coredns/coredns/plugin/kubernetes/object.(*Endpoints).GetNamespace(0x0, 0x0, 0x7f563fc9e108)
	/tmp/tmp.BwnuHrciKQ/g/src/github.com/coredns/coredns/plugin/kubernetes/object/endpoint.go:146 +0x5
k8s.io/client-go/tools/cache.MetaNamespaceKeyFunc(0x1b517a0, 0x0, 0x158352a, 0x1b4efa0, 0x0, 0x0)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/store.go:84 +0x105
k8s.io/client-go/tools/cache.DeletionHandlingMetaNamespaceKeyFunc(0x1b517a0, 0x0, 0x1, 0x0, 0x203000, 0x203000)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/controller.go:264 +0x6a
k8s.io/client-go/tools/cache.(*cache).Delete(0xc00012dbe0, 0x1b517a0, 0x0, 0x0, 0x18)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/store.go:144 +0x42
github.com/coredns/coredns/plugin/kubernetes.newdnsController.func1.1(0x1970160, 0xc000b368a0, 0x1, 0xc000b368a0)
	/tmp/tmp.BwnuHrciKQ/g/src/github.com/coredns/coredns/plugin/kubernetes/controller.go:167 +0x5af
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0001440b0, 0xc00013ef30, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/delta_fifo.go:422 +0x235
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000520f00)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/controller.go:153 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0000d0f80)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0000d0f80, 0x3b9aca00, 0x0, 0xc00016a701, 0xc0005281e0)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc000520f00, 0xc0005281e0)
	/tmp/tmp.BwnuHrciKQ/g/pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/controller.go:125 +0x2c1
created by github.com/coredns/coredns/plugin/kubernetes.(*dnsControl).Run
	/tmp/tmp.BwnuHrciKQ/g/src/github.com/coredns/coredns/plugin/kubernetes/controller.go:304 +0x12b
```
- OS (e.g: `cat /etc/os-release`): k8s 1.18.9, ubuntu focal fossa (kops stable os image)
- Others:

**Comment by zouyee** [comment]
issue: https://github.com/coredns/coredns/issues/4022
related answer： https://github.com/coredns/coredns/issues/4022#issuecomment-663513766

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] coredns pods ..." ]
>#4022

/label duplicate
/close
/lock
