### ISSUE TITLE
Azure plugin crashing

### ISSUE THREAD

**Issue by d-rupp** [coredns/coredns#4818]
**What happened**:
CoreDNS caught a panic and afterwards stopped serving one of the zones using the Azure plugin even though the logfile states it recovered.

**What you expected to happen**:
We expect the plugin not to crash.

**How to reproduce it (as minimally and precisely as possible)**:
I have no idea how to reproduce it, but it happens regularly in our datacenter with the highest load. But i am not convinced that this is load-dependent as our overall load is still pretty low compared to others (below 50 requests per second). 

**Environment**:

- the version of CoreDNS: 1.8.4
- Corefile: 
The Corefile is generated from a template and quite long. Here is an abbreviated version.
```
. {
  forward . 127.0.0.1:5301 127.0.0.1:5303
  errors
  prometheus 0.0.0.0:9153
  health 0.0.0.0:8080
  ebug
}

10.in-addr.arpa. {
  azure rg-dns-arpa:10.in-addr.arpa {
    tenant tenant-id
    client client-id
    secret secret-token
    subscription subscription-id
    access private
    fallthrough
  }
  forward . 127.0.0.1:5301 127.0.0.1:5303
  errors
  prometheus 0.0.0.0:9153
}
16.172.in-addr.arpa. {
  azure rg-dns-arpa:16.172.in-addr.arpa {
    tenant tenant-id
    client client-id
    secret secret-token
    subscription subscription-id
    access private
    fallthrough
  }
  forward . 127.0.0.1:5301 127.0.0.1:5303
  errors
  prometheus 0.0.0.0:9153
}

r.t. {
  azure rg-dns-i:r.t {
    tenant tenant-id
    client client-id
    secret secret-token
    subscription subscription-id
    access private
    fallthrough
  }
  azure rg-dns-i-f:f.r.t {
<--- repeats 10 times for individual subzones of r.t --->
    tenant tenant-id
    client client-id
    secret secret-token
    subscription subscription-id
    access private
    fallthrough
  }
  forward . 127.0.0.1:5301 127.0.0.1:5303
  errors
  prometheus 0.0.0.0:9153
}
r.e. {
  azure rg-dns-a:a.r.e {
    tenant tenant-id
    client client-id
    secret secret-token
    subscription subscription-id
    access private
    fallthrough
  }
  azure rg-dns-e:r.e {
<--- repeats 10 times for individual subzones of r.e --->
    tenant tenant-id
    client client-id
    secret secret-token
    subscription subscription-id
    access private
    fallthrough
  }
  forward . 127.0.0.1:5301 127.0.0.1:5303
  errors
  prometheus 0.0.0.0:9153
}
r.m. {
  azure rg-dns-com:r.m {
    tenant tenant-id
    client client-id
    secret secret-token
    subscription subscription-id
    access private
    fallthrough
  }
  azure rg-dns-a:a.r.m {
     <--- repeats 70 times for individual subzones of r.m --->
  }

  forward . 127.0.0.1:5301 127.0.0.1:5303
  errors
  prometheus 0.0.0.0:9153
}

r.r. {
  forward . 10.11.8.1 10.11.8.102
  errors
  prometheus 0.0.0.0:9153
}

b.e. {
  forward . 10.204.4.92 10.220.3.118
  errors
  prometheus 0.0.0.0:9153
}

s.c. {
  forward . 10.204.4.92 10.220.3.118
  errors
  prometheus 0.0.0.0:9153
}

.:5301 {
  forward . tls://8.8.8.8 tls://8.8.4.4 {
    tls_servername dns.google
  }
  errors
  cache
  prometheus 0.0.0.0:9153
}

.:5302 {
  forward . tls://1.1.1.1 tls://1.0.0.1 {
    tls_servername cloudflare-dns.com
  }
  errors
  cache
  prometheus 0.0.0.0:9153
}

.:5303 {
  forward . tls://9.9.9.9 tls://149.112.112.112 {
    tls_servername dns.quad9.net
  }
  errors
  cache
  prometheus 0.0.0.0:9153
```

- logs, if applicable: There are the traces that come up after enabling errors. They all look the same
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6e23b3]

goroutine 4803757 [running]:
github.com/miekg/dns.PrevLabel(0x0, 0x19, 0x1, 0x15, 0x0)
/tmp/tmp.yKFifwyuJG/g/pkg/mod/github.com/miekg/dns@v1.1.42/labels.go:163 +0x33
github.com/coredns/coredns/plugin/file/tree.less(0xc001be69a0, 0x19, 0x0, 0x19, 0x1)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/plugin/file/tree/less.go:23 +0xc6
github.com/coredns/coredns/plugin/file/tree.Less(0xc001659170, 0xc001be69a0, 0x19, 0x1)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/plugin/file/tree/elem.go:101 +0x57
github.com/coredns/coredns/plugin/file/tree.(*Node).search(0xc000eccaa0, 0xc001be69a0, 0x19, 0x3, 0x2)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/plugin/file/tree/tree.go:155 +0x50
github.com/coredns/coredns/plugin/file/tree.(*Tree).Search(0xc00172ed10, 0xc001be69a0, 0x19, 0x2, 0xc001be69a0)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/plugin/file/tree/tree.go:145 +0x4b
github.com/coredns/coredns/plugin/file.(*Zone).Lookup(0xc0008c4e00, 0x23b7678, 0xc0005b6960, 0xc0015201b0, 0x23ca2f8, 0xc00029e4c0, 0x0, 0x0, 0x200, 0xc001be69a0, ...)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/plugin/file/lookup.go:95 +0x21e
github.com/coredns/coredns/plugin/azure.(*Azure).ServeDNS(0xc00035c960, 0x23b7678, 0xc0005b6960, 0x23ca2f8, 0xc00029e4c0, 0xc0015201b0, 0x8, 0x1, 0x2)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/plugin/azure/azure.go:321 +0x298
github.com/coredns/coredns/plugin.NextOrFailure(0x2070238, 0x6, 0x2386a80, 0xc00035c960, 0x23b7678, 0xc0005b6960, 0x23ca2f8, 0xc00029e4c0, 0xc0015201b0, 0x0, ...)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/plugin/plugin.go:80 +0xfa
github.com/coredns/coredns/plugin/errors.(*errorHandler).ServeDNS(0xc00079e840, 0x23b7678, 0xc0005b6960, 0x23ca2f8, 0xc00029e4c0, 0xc0015201b0, 0xc000d09b70, 0x40dbbb, 0xc00029e4c0)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/plugin/errors/errors.go:83 +0xa6
github.com/coredns/coredns/plugin.NextOrFailure(0x20766ee, 0xa, 0x2386b48, 0xc00079e840, 0x23b7678, 0xc0005b6960, 0x23ca2f8, 0xc00029e4c0, 0xc0015201b0, 0x0, ...)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/plugin/plugin.go:80 +0xfa
github.com/coredns/coredns/plugin/metrics.(*Metrics).ServeDNS(0xc0007a0ab0, 0x23b7678, 0xc0005b6960, 0x23ca400, 0xc000e898c0, 0xc0015201b0, 0xc000700000, 0x0, 0xc000d09df8)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/plugin/metrics/handler.go:27 +0x265
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS(0xc000d9a9c0, 0x23b7678, 0xc0005b6960, 0x23ca400, 0xc000e898c0, 0xc0015201b0)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/core/dnsserver/server.go:250 +0x69c
github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1(0x23cbed0, 0xc001b09200, 0xc0015201b0)
/tmp/tmp.yKFifwyuJG/g/src/github.com/coredns/coredns/core/dnsserver/server.go:128 +0xf7
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc000736080, 0x23cbed0, 0xc001b09200, 0xc0015201b0)
/tmp/tmp.yKFifwyuJG/g/pkg/mod/github.com/miekg/dns@v1.1.42/server.go:37 +0x44
github.com/miekg/dns.(*Server).serveDNS(0xc000bf8000, 0xc000d62400, 0x2a, 0x200, 0xc001b09200)
/tmp/tmp.yKFifwyuJG/g/pkg/mod/github.com/miekg/dns@v1.1.42/server.go:651 +0x2fd
github.com/miekg/dns.(*Server).serveUDPPacket(0xc000bf8000, 0xc0009d22d4, 0xc000d62400, 0x2a, 0x200, 0x23c8db8, 0xc0007222d0, 0xc001f6f360, 0x0, 0x0)
/tmp/tmp.yKFifwyuJG/g/pkg/mod/github.com/miekg/dns@v1.1.42/server.go:591 +0xed
created by github.com/miekg/dns.(*Server).serveUDP
/tmp/tmp.yKFifwyuJG/g/pkg/mod/github.com/miekg/dns@v1.1.42/server.go:521 +0x395
```

- OS: RHEL7.9 on a physical machine, CoreDNS running in a Container

**Comment by d-rupp** [comment]
I will update to the latest version and report if the issue still exists
