### ISSUE TITLE
Panic in cache during prefetch due to empty dns.Msg

### ISSUE THREAD

**Issue by ReneHollander** [coredns/coredns#6051]
**What happened**:
Using a cache with a prefetch results in a panic due to an out of bounds array access.

**What you expected to happen**:
CoreDNS doesn't panic and crash.

**How to reproduce it (as minimally and precisely as possible)**:

See config below. Digging through the code I could not come up with a way to understand which item is getting refreshed. I patched CoreDNS to add a log and not crash. See logs below for result:
```
diff --git a/plugin/cache/cache.go b/plugin/cache/cache.go
index 563b2abb..f8ba1079 100644
--- a/plugin/cache/cache.go
+++ b/plugin/cache/cache.go
@@ -89,6 +89,11 @@ func key(qname string, m *dns.Msg, t response.Type, do bool) (bool, uint64) {
 		return false, 0
 	}
 
+	if len(m.Question) == 0 {
+		log.Warningf("Tried to cache entry with empty question: %s", m)
+		return false, 0
+	}
+
 	return true, hash(qname, m.Question[0].Qtype, do)
 }
```

Seems to be that something generates an empty `dns.Msg` that is then attempted to be cached.

**Anything else we need to know?**:

I am using the blocklist plugin: https://github.com/relekang/coredns-blocklist

**Environment**:

- the version of CoreDNS: 1.10.1
- Corefile:
```
(common) {
  prometheus
  errors
  dnstap tcp://127.0.0.1:6000 full {
    identity [ redacted ]
  }
}
. {
  import common
  blocklist [ redacted ]
  unbound
  cache {
    prefetch 1 30m
  }
}
[ redacted ]
```
- logs, if applicable:
   - without patch:
```
2023-04-24T21:15:45+02:00	[INFO] plugin/blocklist: Loading from [ redacted ]
2023-04-24T21:15:50+02:00	[INFO] plugin/blocklist: Loaded 2273084 domains from [ redacted ]
2023-04-24T21:15:50+02:00	[WARNING] An external plugin (github.com/coredns/unbound@v0.0.7/setup.go line 63) is using the deprecated function Normalize. This will be removed in a future versions of CoreDNS. The plugin should be updated to use OriginsFromArgsOrServerBlock or NormalizeExact instead.
2023-04-24T21:15:53+02:00	linux/amd64, go1.20.3,
2023-04-24T21:15:53+02:00	CoreDNS-1.10.1
2023-04-24T21:15:53+02:00	[ redacted ]
2023-04-24T21:15:53+02:00	[ redacted ]
2023-04-24T21:15:53+02:00	[ redacted ]
2023-04-24T21:15:53+02:00	.:53
2023-04-24T21:41:29+02:00		github.com/coredns/coredns/plugin/cache/cache.go:92 +0x85
2023-04-24T21:41:29+02:00	github.com/coredns/coredns/plugin/cache.key({0xc0093cbc10?, 0x1?}, 0x0?, 0x0?, 0x68?)
2023-04-24T21:41:29+02:00	goroutine 1799 [running]:
2023-04-24T21:41:29+02:00	panic: runtime error: index out of range [0] with length 0
2023-04-24T21:41:29+02:00		github.com/coredns/coredns/plugin/cache/handler.go:64 +0x9ed
2023-04-24T21:41:29+02:00	created by github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS
2023-04-24T21:41:29+02:00		github.com/coredns/coredns/plugin/cache/handler.go:96 +0x1a5
2023-04-24T21:41:29+02:00	github.com/coredns/coredns/plugin/cache.(*Cache).doPrefetch(0xc000205100, {0x26b6d68, 0xc000d42240}, {0xc000464cf0, {0x26be148, 0xc000464c60}, {0x0, 0x0}, 0x4d0, 0x0, ...}, ...)
2023-04-24T21:41:29+02:00		github.com/coredns/coredns/plugin/cache/handler.go:107
2023-04-24T21:41:29+02:00	github.com/coredns/coredns/plugin/cache.(*Cache).doRefresh(...)
2023-04-24T21:41:29+02:00	github.com/coredns/coredns/plugin.NextOrFailure({0x21eddc2?, 0xc000d42480?}, {0x26a7098, 0xc0008c0120}, {0x26b6d68, 0xc000d42240}, {0x26be040, 0xc0002cad00}, 0x200?)
2023-04-24T21:41:29+02:00		github.com/relekang/coredns-blocklist@v1.9.0/blocklist.go:86 +0x366
2023-04-24T21:41:29+02:00	github.com/relekang/coredns-blocklist.Blocklist.ServeDNS({0xc0008c05d0, 0xc0008c0030, {0x26a1738, 0xc0000b60a0}, 0x0}, {0x26b6d68, 0xc000d42240}, {0x26be040, 0xc0002cad00}, 0xc000464cf0)
2023-04-24T21:41:29+02:00		github.com/coredns/coredns/plugin/plugin.go:80 +0x27e
2023-04-24T21:41:29+02:00	github.com/coredns/coredns/plugin.NextOrFailure({0x21f3f24?, 0xc0008c0030?}, {0x26a1738, 0xc0000b60a0}, {0x26b6d68, 0xc000d42240}, {0x26be040, 0xc0002cad00}, 0xc0046e9b90?)
2023-04-24T21:41:29+02:00		github.com/coredns/unbound@v0.0.7/unbound.go:140 +0x562
2023-04-24T21:41:29+02:00	github.com/coredns/unbound.(*Unbound).ServeDNS(0xc0000b60a0, {0x26b6d68, 0xc000d42240}, {0x26be040, 0xc0002cad00}, 0xc000464cf0)
2023-04-24T21:41:29+02:00		github.com/coredns/coredns/plugin/cache/cache.go:180 +0x107
2023-04-24T21:41:29+02:00	github.com/coredns/coredns/plugin/cache.(*ResponseWriter).WriteMsg(0xc0002cad00, 0xc000464ea0)
```
   - with patch:
```
2023-04-24T21:45:35+02:00	[INFO] plugin/blocklist: Loading from https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/ultimate.txt
2023-04-24T21:45:36+02:00	[INFO] plugin/blocklist: Loaded 2273084 domains from https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/ultimate.txt
2023-04-24T21:45:36+02:00	[WARNING] An external plugin (github.com/coredns/unbound@v0.0.7/setup.go line 63) is using the deprecated function Normalize. This will be removed in a future versions of CoreDNS. The plugin should be updated to use OriginsFromArgsOrServerBlock or NormalizeExact instead.
2023-04-24T21:45:38+02:00	linux/amd64, go1.20.3,
2023-04-24T21:45:38+02:00	CoreDNS-1.10.1
2023-04-24T21:45:38+02:00	[ redacted ]
2023-04-24T21:45:38+02:00	[ redacted ]
2023-04-24T21:45:38+02:00	[ redacted ]
2023-04-24T21:45:38+02:00	.:53
2023-04-24T22:01:28+02:00	;; flags:; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
2023-04-24T22:01:28+02:00	[WARNING] plugin/cache: Tried to cache entry with empty question: ;; opcode: QUERY, status: NOERROR, id: 5290
2023-04-24T22:01:28+02:00	;; flags:; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
2023-04-24T22:01:28+02:00	[WARNING] plugin/cache: Tried to cache entry with empty question: ;; opcode: QUERY, status: NOERROR, id: 37132
```
- OS (e.g: `cat /etc/os-release`):
```
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="23.05.20230414.abe7316"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 23.05 (Stoat)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="23.05 (Stoat)"
VERSION_CODENAME=stoat
VERSION_ID="23.05"
```
- Others:

**Comment by chrisohaver** [comment]
I suspect this is a bug in one of the external plugins (blocklist, unbound, or other possibly redacted external plugins)  returning an invalid response. 

The proposed fix does prevent a crash and it logs a warning, but does so somewhat anonymously. It would be great if we could identify which plugin returned the malformed response, and even better to find the source of the bug and fix it.

**Comment by ReneHollander** [comment]
The issue is not in the blocklist plugin. Error still occurs even after I disabled it:
```
2023-04-28T19:19:34+02:00	[WARNING] An external plugin (github.com/coredns/unbound@v0.0.7/setup.go line 63) is using the deprecated function Normalize. This will be removed in a future versions of CoreDNS. The plugin should be updated to use OriginsFromArgsOrServerBlock or NormalizeExact instead.
2023-04-28T19:19:34+02:00	linux/amd64, go1.20.3,
2023-04-28T19:19:34+02:00	CoreDNS-1.10.1
2023-04-28T19:19:34+02:00	[ redacted ]
2023-04-28T19:19:34+02:00	[ redacted ]
2023-04-28T19:19:34+02:00	[ redacted ]
2023-04-28T19:19:34+02:00	.:53
2023-04-28T19:41:28+02:00	;; flags:; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
2023-04-28T19:41:28+02:00	[WARNING] plugin/cache: Tried to cache entry with empty question: ;; opcode: QUERY, status: NOERROR, id: 13577
2023-04-28T19:51:51+02:00	;; flags:; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
2023-04-28T19:51:51+02:00	[WARNING] plugin/cache: Tried to cache entry with empty question: ;; opcode: QUERY, status: NOERROR, id: 8227
```

Disabling both the blocklist plugin and unbound plugin and replacing it with a forward to 1.1.1.1 resolves the crash.

So I guess the issue is in the unbound plugin.

I will continue investigating. Probably need some debugging outputs in the unbound plugin to see what happens during prefetch here...
